name: Expo Publish
on:
  push:
    branches:
      - master
jobs:
  Build-for-android:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - uses: actions/setup-java@v1.4.3
        with:
          java-version: '9.0.4'
          java-package: jdk
          architecture: x64
      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.11.0
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}

      - name: Install deps
        run: |
          cd ./app
          yarn install

      - name: Build Android App Bundle
        run: |
          cd ./app
          npx eas-cli build --platform android --non-interactive

  Push-to-Playstore:
    needs: [Build-for-android]
    runs-on: macos-latest
    env:
      GOOGLE_SERVICE_JSON: ${{ secrets.GOOGLE_SERVICE }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Write google-service.json
        run: |
          touch ./app/google-services.json
          echo $GOOGLE_SERVICE_JSON >> ./app/google-services.json

      - uses: expo/expo-github-action@v5
        with:
          expo-version: 4.11.0
          expo-username: ${{ secrets.EXPO_USERNAME }}
          expo-password: ${{ secrets.EXPO_PASSWORD }}

      - name: Upload to Google Play Console
        run: |
          cd ./app
          npx eas-cli submit -p android --latest
